<div class="greet welcome" data-bind="scope: 'customer'">
    <!-- ko if: customer().is_logged_in  -->
    <span class="logged-in"
          data-bind="text: new String('<?= $block->escapeHtml(__('Customer Firstname %1', '%1')) ?>').replace('%1', customer().firstname)">
    </span>
    <span class="logged-in"
          data-bind="text: new String('<?= $block->escapeHtml(__('Customer Lastname %1', '%1')) ?>').replace('%1', customer().lastname)">
    </span>
    <!-- /ko -->
    <!-- ko ifnot: customer().is_logged_in  -->
    <span class="not-logged-in"
          data-bind='html:"<?= $block->escapeHtml(__("Please <a href='%1'>login</a>", $block->getUrl('customer/account/login'))) ?>"'>
    </span>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "customer": {
                    "component": "Magento_Customer/js/view/customer"
                }
            }
        }
    }
}


</script>
